### ISSUE TITLE
No file extention when downloading

### ISSUE THREAD

**Issue by bairhys** [mrmn2/PdfDing#28]
When downloading, there is no file extension on the downloaded file on Windows with Chrome and Firefox.

**Comment by mrmn2** [comment]
I set this on purpose as otherwise my browser (firefox based) would open a new tab instead of starting the download. I thought I would leave it like this until someone complains :D. Since then I have discovered that I can change this in the browser's settings. 

I will adjust the file extension and it will be part of the next release.

**Comment by bairhys** [comment]
Yes true, opening as a new tab would be annoying!
